# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: my-fave-food_development

test:
  <<: *default
  database: my-fave-food_test

production:
  <<: *default
  database: my-fave-food_production
  username: my-fave-food
  password: <%= ENV['MY-FAVE-FOOD_DATABASE_PASSWORD'] %>
